/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m9;

import java.sql.Connection; 

import java.sql.DriverManager; 

import java.sql.ResultSet; 

import java.sql.Statement; 

import javax.swing.JOptionPane; 
/**
 *
 * @author User
 */
public class CelsiusToFahrenheit extends javax.swing.JFrame {
private Statement stmt;
    /**
     * Creates new form CelsiusToFahrenheit
     */
    public CelsiusToFahrenheit() {
        initComponents();
//create the connection here 

            try{ 

                //driver for the connection to the database 

                Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance(); 

                //JOptionPane.showMessageDialog(null,"Driver Connected"); 
                 //point to the database 

                 String url ="jdbc:derby://localhost:1527/Temperatures;create=true;user=root;password=sac123"; 

                // JOptionPane.showMessageDialog(null,"Database Connected"); 

                 //Connection Class to connect to the database 

                 Connection connection = DriverManager.getConnection(url); 

                 stmt = connection.createStatement(); 
    }catch(Exception ex) 

    { 

        JOptionPane.showMessageDialog(null,ex.toString()); 

    } 

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTemp = new javax.swing.JTextField();
        btnToFahrenheit = new javax.swing.JButton();
        btnToCelsius = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Conversion");

        jLabel1.setText("Temperature:");

        txtTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempActionPerformed(evt);
            }
        });

        btnToFahrenheit.setText("Convert to Fahrenheit");
        btnToFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToFahrenheitActionPerformed(evt);
            }
        });

        btnToCelsius.setText("Convert to Celsius");
        btnToCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToCelsiusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnToFahrenheit)
                        .addGap(18, 18, 18)
                        .addComponent(btnToCelsius))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToFahrenheit)
                    .addComponent(btnToCelsius))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempActionPerformed

    private void btnToFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToFahrenheitActionPerformed
        // TODO add your handling code here:

        try{ 
        float celsius = Float.valueOf(txtTemp.getText().toString());
        
        float fahrenheit = (float) ((celsius * 1.8 ) + 32.0);

         

            String queryString= "Insert into ROOT.TEMPERATURESTABLE " + "(FAHRENHEIT, CELSIUS)"  

                    + "Values"+ 

                    "('"+fahrenheit+"','"+celsius+"')"; 

                    

            stmt.execute(queryString); 

                    JOptionPane.showMessageDialog(null, "Conversion completed"); 

             }catch(Exception ex) 

             { 

                 JOptionPane.showMessageDialog(null, ex.toString()); 

             } 
                           
         
    }//GEN-LAST:event_btnToFahrenheitActionPerformed

    private void btnToCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToCelsiusActionPerformed
        // TODO add your handling code here:

        try{ 
        float fahrenheit = Float.valueOf(txtTemp.getText().toString());
        
        float celsius = (float) (((fahrenheit - 32.0)*5.0)/9.0);

         

            String queryString= "Insert into ROOT.TEMPERATURESTABLE " + "(FAHRENHEIT, CELSIUS)"  

                    + "Values"+ 

                    "('"+fahrenheit+"','"+celsius+"')"; 

                    

            stmt.execute(queryString); 

                    JOptionPane.showMessageDialog(null, "Conversion completed"); 

             }catch(Exception ex) 

             { 

                 JOptionPane.showMessageDialog(null, ex.toString()); 

             } 
    }//GEN-LAST:event_btnToCelsiusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CelsiusToFahrenheit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CelsiusToFahrenheit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CelsiusToFahrenheit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CelsiusToFahrenheit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CelsiusToFahrenheit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnToCelsius;
    private javax.swing.JButton btnToFahrenheit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables
}
